--INTERVIEW QUESTIONS -

CREATE OR REPLACE TYPE TTS IS TABLE OF VARCHAR2(50);
/

SELECT * FROM USER_TYPES;

CREATE OR REPLACE PROCEDURE SP_COLLECTIONS( P_RESULT OUT TTS )AS
BEGIN
P_RESULT = TTS('ORACLE', 'JAVA', 'PYTHON');
END;
/


DECLARE
С TTS;
BEGIN
SP_COLLECTIONS( P_RESULT => C);
DBMS_OUTPUT.PUT_LINE(C.COUNT);
END;
/
-------------------------------------------

CREATE OR REPLACE FUNCTION FN_COLLECTION RETURN TTS AS
 FNAME TTS;
BEGIN
	SELECT FIRST_NAME BULK COLLECT INTO FNAME FROM EMPLOYEES;
	RETURN FNAME;
 END;
 /
 
 
 

